/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as SubmitMissionRouteImport } from './routes/submit-mission'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SampleAnswerOrderIdRouteImport } from './routes/sample-answer.$orderId'
import { Route as ReportOrderIdRouteImport } from './routes/report.$orderId'
import { Route as MyReportsRouteImport } from './routes/my.reports'
import { Route as MyRecommendationsRouteImport } from './routes/my.recommendations'
import { Route as MissionOrderIdRouteImport } from './routes/mission.$orderId'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as AdminShareVerificationsRouteImport } from './routes/admin/share-verifications'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminMissionsRouteImport } from './routes/admin/missions'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as ApiPublicPayappCallbackRouteImport } from './routes/api/public/payapp-callback'
import { Route as ApiPublicOrderSubmittedNotifyRouteImport } from './routes/api/public/order-submitted-notify'
import { Route as ApiPublicMissionRequestRouteImport } from './routes/api/public/mission-request'
import { Route as AdminMissionsMissionIdRouteImport } from './routes/admin.missions.$missionId'
import { Route as ExperiencesSlugMissionsMissionIdRouteImport } from './routes/experiences.$slug.missions.$missionId'

const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitMissionRoute = SubmitMissionRouteImport.update({
  id: '/submit-mission',
  path: '/submit-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SampleAnswerOrderIdRoute = SampleAnswerOrderIdRouteImport.update({
  id: '/sample-answer/$orderId',
  path: '/sample-answer/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportOrderIdRoute = ReportOrderIdRouteImport.update({
  id: '/report/$orderId',
  path: '/report/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MyRoute,
} as any)
const MyRecommendationsRoute = MyRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => MyRoute,
} as any)
const MissionOrderIdRoute = MissionOrderIdRouteImport.update({
  id: '/mission/$orderId',
  path: '/mission/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShareVerificationsRoute = AdminShareVerificationsRouteImport.update({
  id: '/share-verifications',
  path: '/share-verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsRoute = AdminMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPayappCallbackRoute = ApiPublicPayappCallbackRouteImport.update({
  id: '/api/public/payapp-callback',
  path: '/api/public/payapp-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderSubmittedNotifyRoute =
  ApiPublicOrderSubmittedNotifyRouteImport.update({
    id: '/api/public/order-submitted-notify',
    path: '/api/public/order-submitted-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMissionRequestRoute = ApiPublicMissionRequestRouteImport.update({
  id: '/api/public/mission-request',
  path: '/api/public/mission-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMissionsMissionIdRoute = AdminMissionsMissionIdRouteImport.update({
  id: '/$missionId',
  path: '/$missionId',
  getParentRoute: () => AdminMissionsRoute,
} as any)
const ExperiencesSlugMissionsMissionIdRoute =
  ExperiencesSlugMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => ExperiencesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/simulations': typeof SimulationsRoute
  '/submit-mission': typeof SubmitMissionRoute
  '/submitted': typeof SubmittedRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/missions': typeof AdminMissionsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/share-verifications': typeof AdminShareVerificationsRoute
  '/experiences/$slug': typeof ExperiencesSlugRouteWithChildren
  '/mission/$orderId': typeof MissionOrderIdRoute
  '/my/recommendations': typeof MyRecommendationsRoute
  '/my/reports': typeof MyReportsRoute
  '/report/$orderId': typeof ReportOrderIdRoute
  '/sample-answer/$orderId': typeof SampleAnswerOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/admin/missions/$missionId': typeof AdminMissionsMissionIdRoute
  '/api/public/mission-request': typeof ApiPublicMissionRequestRoute
  '/api/public/order-submitted-notify': typeof ApiPublicOrderSubmittedNotifyRoute
  '/api/public/payapp-callback': typeof ApiPublicPayappCallbackRoute
  '/experiences/$slug/missions/$missionId': typeof ExperiencesSlugMissionsMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/simulations': typeof SimulationsRoute
  '/submit-mission': typeof SubmitMissionRoute
  '/submitted': typeof SubmittedRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/missions': typeof AdminMissionsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/share-verifications': typeof AdminShareVerificationsRoute
  '/experiences/$slug': typeof ExperiencesSlugRouteWithChildren
  '/mission/$orderId': typeof MissionOrderIdRoute
  '/my/recommendations': typeof MyRecommendationsRoute
  '/my/reports': typeof MyReportsRoute
  '/report/$orderId': typeof ReportOrderIdRoute
  '/sample-answer/$orderId': typeof SampleAnswerOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/admin/missions/$missionId': typeof AdminMissionsMissionIdRoute
  '/api/public/mission-request': typeof ApiPublicMissionRequestRoute
  '/api/public/order-submitted-notify': typeof ApiPublicOrderSubmittedNotifyRoute
  '/api/public/payapp-callback': typeof ApiPublicPayappCallbackRoute
  '/experiences/$slug/missions/$missionId': typeof ExperiencesSlugMissionsMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/simulations': typeof SimulationsRoute
  '/submit-mission': typeof SubmitMissionRoute
  '/submitted': typeof SubmittedRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/missions': typeof AdminMissionsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/share-verifications': typeof AdminShareVerificationsRoute
  '/experiences/$slug': typeof ExperiencesSlugRouteWithChildren
  '/mission/$orderId': typeof MissionOrderIdRoute
  '/my/recommendations': typeof MyRecommendationsRoute
  '/my/reports': typeof MyReportsRoute
  '/report/$orderId': typeof ReportOrderIdRoute
  '/sample-answer/$orderId': typeof SampleAnswerOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/admin/missions/$missionId': typeof AdminMissionsMissionIdRoute
  '/api/public/mission-request': typeof ApiPublicMissionRequestRoute
  '/api/public/order-submitted-notify': typeof ApiPublicOrderSubmittedNotifyRoute
  '/api/public/payapp-callback': typeof ApiPublicPayappCallbackRoute
  '/experiences/$slug/missions/$missionId': typeof ExperiencesSlugMissionsMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/pricing'
    | '/simulations'
    | '/submit-mission'
    | '/submitted'
    | '/admin/feedback'
    | '/admin/jobs'
    | '/admin/missions'
    | '/admin/requests'
    | '/admin/share-verifications'
    | '/experiences/$slug'
    | '/mission/$orderId'
    | '/my/recommendations'
    | '/my/reports'
    | '/report/$orderId'
    | '/sample-answer/$orderId'
    | '/admin/'
    | '/experiences/'
    | '/admin/missions/$missionId'
    | '/api/public/mission-request'
    | '/api/public/order-submitted-notify'
    | '/api/public/payapp-callback'
    | '/experiences/$slug/missions/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/pricing'
    | '/simulations'
    | '/submit-mission'
    | '/submitted'
    | '/admin/feedback'
    | '/admin/jobs'
    | '/admin/missions'
    | '/admin/requests'
    | '/admin/share-verifications'
    | '/experiences/$slug'
    | '/mission/$orderId'
    | '/my/recommendations'
    | '/my/reports'
    | '/report/$orderId'
    | '/sample-answer/$orderId'
    | '/admin'
    | '/experiences'
    | '/admin/missions/$missionId'
    | '/api/public/mission-request'
    | '/api/public/order-submitted-notify'
    | '/api/public/payapp-callback'
    | '/experiences/$slug/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/pricing'
    | '/simulations'
    | '/submit-mission'
    | '/submitted'
    | '/admin/feedback'
    | '/admin/jobs'
    | '/admin/missions'
    | '/admin/requests'
    | '/admin/share-verifications'
    | '/experiences/$slug'
    | '/mission/$orderId'
    | '/my/recommendations'
    | '/my/reports'
    | '/report/$orderId'
    | '/sample-answer/$orderId'
    | '/admin/'
    | '/experiences/'
    | '/admin/missions/$missionId'
    | '/api/public/mission-request'
    | '/api/public/order-submitted-notify'
    | '/api/public/payapp-callback'
    | '/experiences/$slug/missions/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SimulationsRoute: typeof SimulationsRoute
  SubmitMissionRoute: typeof SubmitMissionRoute
  SubmittedRoute: typeof SubmittedRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRouteWithChildren
  MissionOrderIdRoute: typeof MissionOrderIdRoute
  ReportOrderIdRoute: typeof ReportOrderIdRoute
  SampleAnswerOrderIdRoute: typeof SampleAnswerOrderIdRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  ApiPublicMissionRequestRoute: typeof ApiPublicMissionRequestRoute
  ApiPublicOrderSubmittedNotifyRoute: typeof ApiPublicOrderSubmittedNotifyRoute
  ApiPublicPayappCallbackRoute: typeof ApiPublicPayappCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-mission': {
      id: '/submit-mission'
      path: '/submit-mission'
      fullPath: '/submit-mission'
      preLoaderRoute: typeof SubmitMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sample-answer/$orderId': {
      id: '/sample-answer/$orderId'
      path: '/sample-answer/$orderId'
      fullPath: '/sample-answer/$orderId'
      preLoaderRoute: typeof SampleAnswerOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$orderId': {
      id: '/report/$orderId'
      path: '/report/$orderId'
      fullPath: '/report/$orderId'
      preLoaderRoute: typeof ReportOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/reports': {
      id: '/my/reports'
      path: '/reports'
      fullPath: '/my/reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/recommendations': {
      id: '/my/recommendations'
      path: '/recommendations'
      fullPath: '/my/recommendations'
      preLoaderRoute: typeof MyRecommendationsRouteImport
      parentRoute: typeof MyRoute
    }
    '/mission/$orderId': {
      id: '/mission/$orderId'
      path: '/mission/$orderId'
      fullPath: '/mission/$orderId'
      preLoaderRoute: typeof MissionOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/share-verifications': {
      id: '/admin/share-verifications'
      path: '/share-verifications'
      fullPath: '/admin/share-verifications'
      preLoaderRoute: typeof AdminShareVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions': {
      id: '/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AdminMissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payapp-callback': {
      id: '/api/public/payapp-callback'
      path: '/api/public/payapp-callback'
      fullPath: '/api/public/payapp-callback'
      preLoaderRoute: typeof ApiPublicPayappCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-submitted-notify': {
      id: '/api/public/order-submitted-notify'
      path: '/api/public/order-submitted-notify'
      fullPath: '/api/public/order-submitted-notify'
      preLoaderRoute: typeof ApiPublicOrderSubmittedNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mission-request': {
      id: '/api/public/mission-request'
      path: '/api/public/mission-request'
      fullPath: '/api/public/mission-request'
      preLoaderRoute: typeof ApiPublicMissionRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/missions/$missionId': {
      id: '/admin/missions/$missionId'
      path: '/$missionId'
      fullPath: '/admin/missions/$missionId'
      preLoaderRoute: typeof AdminMissionsMissionIdRouteImport
      parentRoute: typeof AdminMissionsRoute
    }
    '/experiences/$slug/missions/$missionId': {
      id: '/experiences/$slug/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/experiences/$slug/missions/$missionId'
      preLoaderRoute: typeof ExperiencesSlugMissionsMissionIdRouteImport
      parentRoute: typeof ExperiencesSlugRoute
    }
  }
}

interface AdminMissionsRouteChildren {
  AdminMissionsMissionIdRoute: typeof AdminMissionsMissionIdRoute
}

const AdminMissionsRouteChildren: AdminMissionsRouteChildren = {
  AdminMissionsMissionIdRoute: AdminMissionsMissionIdRoute,
}

const AdminMissionsRouteWithChildren = AdminMissionsRoute._addFileChildren(
  AdminMissionsRouteChildren,
)

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMissionsRoute: typeof AdminMissionsRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminShareVerificationsRoute: typeof AdminShareVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMissionsRoute: AdminMissionsRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminShareVerificationsRoute: AdminShareVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyRouteChildren {
  MyRecommendationsRoute: typeof MyRecommendationsRoute
  MyReportsRoute: typeof MyReportsRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyRecommendationsRoute: MyRecommendationsRoute,
  MyReportsRoute: MyReportsRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

interface ExperiencesSlugRouteChildren {
  ExperiencesSlugMissionsMissionIdRoute: typeof ExperiencesSlugMissionsMissionIdRoute
}

const ExperiencesSlugRouteChildren: ExperiencesSlugRouteChildren = {
  ExperiencesSlugMissionsMissionIdRoute: ExperiencesSlugMissionsMissionIdRoute,
}

const ExperiencesSlugRouteWithChildren = ExperiencesSlugRoute._addFileChildren(
  ExperiencesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SimulationsRoute: SimulationsRoute,
  SubmitMissionRoute: SubmitMissionRoute,
  SubmittedRoute: SubmittedRoute,
  ExperiencesSlugRoute: ExperiencesSlugRouteWithChildren,
  MissionOrderIdRoute: MissionOrderIdRoute,
  ReportOrderIdRoute: ReportOrderIdRoute,
  SampleAnswerOrderIdRoute: SampleAnswerOrderIdRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  ApiPublicMissionRequestRoute: ApiPublicMissionRequestRoute,
  ApiPublicOrderSubmittedNotifyRoute: ApiPublicOrderSubmittedNotifyRoute,
  ApiPublicPayappCallbackRoute: ApiPublicPayappCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
