/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BizRouteImport } from './routes/biz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationIdRouteImport } from './routes/simulation.$id'
import { Route as BizReviewRouteImport } from './routes/biz_.review'
import { Route as AdminSimulationsRouteImport } from './routes/admin.simulations'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BizRoute = BizRouteImport.update({
  id: '/biz',
  path: '/biz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationIdRoute = SimulationIdRouteImport.update({
  id: '/simulation/$id',
  path: '/simulation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BizReviewRoute = BizReviewRouteImport.update({
  id: '/biz_/review',
  path: '/biz/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSimulationsRoute = AdminSimulationsRouteImport.update({
  id: '/admin/simulations',
  path: '/admin/simulations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biz': typeof BizRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/onboarding': typeof OnboardingRoute
  '/simulations': typeof SimulationsRoute
  '/start': typeof StartRoute
  '/admin/simulations': typeof AdminSimulationsRoute
  '/biz/review': typeof BizReviewRoute
  '/simulation/$id': typeof SimulationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biz': typeof BizRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/onboarding': typeof OnboardingRoute
  '/simulations': typeof SimulationsRoute
  '/start': typeof StartRoute
  '/admin/simulations': typeof AdminSimulationsRoute
  '/biz/review': typeof BizReviewRoute
  '/simulation/$id': typeof SimulationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biz': typeof BizRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/onboarding': typeof OnboardingRoute
  '/simulations': typeof SimulationsRoute
  '/start': typeof StartRoute
  '/admin/simulations': typeof AdminSimulationsRoute
  '/biz_/review': typeof BizReviewRoute
  '/simulation/$id': typeof SimulationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biz'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/simulations'
    | '/start'
    | '/admin/simulations'
    | '/biz/review'
    | '/simulation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biz'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/simulations'
    | '/start'
    | '/admin/simulations'
    | '/biz/review'
    | '/simulation/$id'
  id:
    | '__root__'
    | '/'
    | '/biz'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/simulations'
    | '/start'
    | '/admin/simulations'
    | '/biz_/review'
    | '/simulation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BizRoute: typeof BizRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRoute
  OnboardingRoute: typeof OnboardingRoute
  SimulationsRoute: typeof SimulationsRoute
  StartRoute: typeof StartRoute
  AdminSimulationsRoute: typeof AdminSimulationsRoute
  BizReviewRoute: typeof BizReviewRoute
  SimulationIdRoute: typeof SimulationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz': {
      id: '/biz'
      path: '/biz'
      fullPath: '/biz'
      preLoaderRoute: typeof BizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$id': {
      id: '/simulation/$id'
      path: '/simulation/$id'
      fullPath: '/simulation/$id'
      preLoaderRoute: typeof SimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz_/review': {
      id: '/biz_/review'
      path: '/biz/review'
      fullPath: '/biz/review'
      preLoaderRoute: typeof BizReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/simulations': {
      id: '/admin/simulations'
      path: '/admin/simulations'
      fullPath: '/admin/simulations'
      preLoaderRoute: typeof AdminSimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BizRoute: BizRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRoute,
  OnboardingRoute: OnboardingRoute,
  SimulationsRoute: SimulationsRoute,
  StartRoute: StartRoute,
  AdminSimulationsRoute: AdminSimulationsRoute,
  BizReviewRoute: BizReviewRoute,
  SimulationIdRoute: SimulationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
