/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpertSimulationsRouteImport } from './routes/expert-simulations'
import { Route as BizRouteImport } from './routes/biz'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationsAllRouteImport } from './routes/simulations_.all'
import { Route as SimulationIdRouteImport } from './routes/simulation.$id'
import { Route as BizReviewRouteImport } from './routes/biz_.review'
import { Route as BizContactRouteImport } from './routes/biz_.contact'
import { Route as BizCoffeeChatRouteImport } from './routes/biz_.coffee-chat'
import { Route as BizApplyRouteImport } from './routes/biz_.apply'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminSimulationsRouteImport } from './routes/admin.simulations'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminExpertSimulationsRouteImport } from './routes/admin.expert-simulations'
import { Route as AdminAiPromptsRouteImport } from './routes/admin.ai-prompts'
import { Route as SimulationIdFeedbackRouteImport } from './routes/simulation.$id.feedback'
import { Route as ExpertSimulationIdReviewRouteImport } from './routes/expert-simulation.$id.review'
import { Route as ExpertSimulationIdFeedbackRouteImport } from './routes/expert-simulation.$id.feedback'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertSimulationsRoute = ExpertSimulationsRouteImport.update({
  id: '/expert-simulations',
  path: '/expert-simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const BizRoute = BizRouteImport.update({
  id: '/biz',
  path: '/biz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsAllRoute = SimulationsAllRouteImport.update({
  id: '/simulations_/all',
  path: '/simulations/all',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationIdRoute = SimulationIdRouteImport.update({
  id: '/simulation/$id',
  path: '/simulation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BizReviewRoute = BizReviewRouteImport.update({
  id: '/biz_/review',
  path: '/biz/review',
  getParentRoute: () => rootRouteImport,
} as any)
const BizContactRoute = BizContactRouteImport.update({
  id: '/biz_/contact',
  path: '/biz/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BizCoffeeChatRoute = BizCoffeeChatRouteImport.update({
  id: '/biz_/coffee-chat',
  path: '/biz/coffee-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BizApplyRoute = BizApplyRouteImport.update({
  id: '/biz_/apply',
  path: '/biz/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSimulationsRoute = AdminSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpertSimulationsRoute = AdminExpertSimulationsRouteImport.update({
  id: '/expert-simulations',
  path: '/expert-simulations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiPromptsRoute = AdminAiPromptsRouteImport.update({
  id: '/ai-prompts',
  path: '/ai-prompts',
  getParentRoute: () => AdminRoute,
} as any)
const SimulationIdFeedbackRoute = SimulationIdFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SimulationIdRoute,
} as any)
const ExpertSimulationIdReviewRoute =
  ExpertSimulationIdReviewRouteImport.update({
    id: '/expert-simulation/$id/review',
    path: '/expert-simulation/$id/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExpertSimulationIdFeedbackRoute =
  ExpertSimulationIdFeedbackRouteImport.update({
    id: '/expert-simulation/$id/feedback',
    path: '/expert-simulation/$id/feedback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biz': typeof BizRoute
  '/expert-simulations': typeof ExpertSimulationsRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/onboarding': typeof OnboardingRoute
  '/simulations': typeof SimulationsRoute
  '/start': typeof StartRoute
  '/admin/ai-prompts': typeof AdminAiPromptsRoute
  '/admin/expert-simulations': typeof AdminExpertSimulationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/simulations': typeof AdminSimulationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/biz/apply': typeof BizApplyRoute
  '/biz/coffee-chat': typeof BizCoffeeChatRoute
  '/biz/contact': typeof BizContactRoute
  '/biz/review': typeof BizReviewRoute
  '/simulation/$id': typeof SimulationIdRouteWithChildren
  '/simulations/all': typeof SimulationsAllRoute
  '/expert-simulation/$id/feedback': typeof ExpertSimulationIdFeedbackRoute
  '/expert-simulation/$id/review': typeof ExpertSimulationIdReviewRoute
  '/simulation/$id/feedback': typeof SimulationIdFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biz': typeof BizRoute
  '/expert-simulations': typeof ExpertSimulationsRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/onboarding': typeof OnboardingRoute
  '/simulations': typeof SimulationsRoute
  '/start': typeof StartRoute
  '/admin/ai-prompts': typeof AdminAiPromptsRoute
  '/admin/expert-simulations': typeof AdminExpertSimulationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/simulations': typeof AdminSimulationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/biz/apply': typeof BizApplyRoute
  '/biz/coffee-chat': typeof BizCoffeeChatRoute
  '/biz/contact': typeof BizContactRoute
  '/biz/review': typeof BizReviewRoute
  '/simulation/$id': typeof SimulationIdRouteWithChildren
  '/simulations/all': typeof SimulationsAllRoute
  '/expert-simulation/$id/feedback': typeof ExpertSimulationIdFeedbackRoute
  '/expert-simulation/$id/review': typeof ExpertSimulationIdReviewRoute
  '/simulation/$id/feedback': typeof SimulationIdFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biz': typeof BizRoute
  '/expert-simulations': typeof ExpertSimulationsRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/onboarding': typeof OnboardingRoute
  '/simulations': typeof SimulationsRoute
  '/start': typeof StartRoute
  '/admin/ai-prompts': typeof AdminAiPromptsRoute
  '/admin/expert-simulations': typeof AdminExpertSimulationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/simulations': typeof AdminSimulationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/biz_/apply': typeof BizApplyRoute
  '/biz_/coffee-chat': typeof BizCoffeeChatRoute
  '/biz_/contact': typeof BizContactRoute
  '/biz_/review': typeof BizReviewRoute
  '/simulation/$id': typeof SimulationIdRouteWithChildren
  '/simulations_/all': typeof SimulationsAllRoute
  '/expert-simulation/$id/feedback': typeof ExpertSimulationIdFeedbackRoute
  '/expert-simulation/$id/review': typeof ExpertSimulationIdReviewRoute
  '/simulation/$id/feedback': typeof SimulationIdFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/biz'
    | '/expert-simulations'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/simulations'
    | '/start'
    | '/admin/ai-prompts'
    | '/admin/expert-simulations'
    | '/admin/inquiries'
    | '/admin/simulations'
    | '/admin/submissions'
    | '/biz/apply'
    | '/biz/coffee-chat'
    | '/biz/contact'
    | '/biz/review'
    | '/simulation/$id'
    | '/simulations/all'
    | '/expert-simulation/$id/feedback'
    | '/expert-simulation/$id/review'
    | '/simulation/$id/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/biz'
    | '/expert-simulations'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/simulations'
    | '/start'
    | '/admin/ai-prompts'
    | '/admin/expert-simulations'
    | '/admin/inquiries'
    | '/admin/simulations'
    | '/admin/submissions'
    | '/biz/apply'
    | '/biz/coffee-chat'
    | '/biz/contact'
    | '/biz/review'
    | '/simulation/$id'
    | '/simulations/all'
    | '/expert-simulation/$id/feedback'
    | '/expert-simulation/$id/review'
    | '/simulation/$id/feedback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/biz'
    | '/expert-simulations'
    | '/login'
    | '/my'
    | '/onboarding'
    | '/simulations'
    | '/start'
    | '/admin/ai-prompts'
    | '/admin/expert-simulations'
    | '/admin/inquiries'
    | '/admin/simulations'
    | '/admin/submissions'
    | '/biz_/apply'
    | '/biz_/coffee-chat'
    | '/biz_/contact'
    | '/biz_/review'
    | '/simulation/$id'
    | '/simulations_/all'
    | '/expert-simulation/$id/feedback'
    | '/expert-simulation/$id/review'
    | '/simulation/$id/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BizRoute: typeof BizRoute
  ExpertSimulationsRoute: typeof ExpertSimulationsRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRoute
  OnboardingRoute: typeof OnboardingRoute
  SimulationsRoute: typeof SimulationsRoute
  StartRoute: typeof StartRoute
  BizApplyRoute: typeof BizApplyRoute
  BizCoffeeChatRoute: typeof BizCoffeeChatRoute
  BizContactRoute: typeof BizContactRoute
  BizReviewRoute: typeof BizReviewRoute
  SimulationIdRoute: typeof SimulationIdRouteWithChildren
  SimulationsAllRoute: typeof SimulationsAllRoute
  ExpertSimulationIdFeedbackRoute: typeof ExpertSimulationIdFeedbackRoute
  ExpertSimulationIdReviewRoute: typeof ExpertSimulationIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-simulations': {
      id: '/expert-simulations'
      path: '/expert-simulations'
      fullPath: '/expert-simulations'
      preLoaderRoute: typeof ExpertSimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz': {
      id: '/biz'
      path: '/biz'
      fullPath: '/biz'
      preLoaderRoute: typeof BizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations_/all': {
      id: '/simulations_/all'
      path: '/simulations/all'
      fullPath: '/simulations/all'
      preLoaderRoute: typeof SimulationsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$id': {
      id: '/simulation/$id'
      path: '/simulation/$id'
      fullPath: '/simulation/$id'
      preLoaderRoute: typeof SimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz_/review': {
      id: '/biz_/review'
      path: '/biz/review'
      fullPath: '/biz/review'
      preLoaderRoute: typeof BizReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz_/contact': {
      id: '/biz_/contact'
      path: '/biz/contact'
      fullPath: '/biz/contact'
      preLoaderRoute: typeof BizContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz_/coffee-chat': {
      id: '/biz_/coffee-chat'
      path: '/biz/coffee-chat'
      fullPath: '/biz/coffee-chat'
      preLoaderRoute: typeof BizCoffeeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz_/apply': {
      id: '/biz_/apply'
      path: '/biz/apply'
      fullPath: '/biz/apply'
      preLoaderRoute: typeof BizApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/simulations': {
      id: '/admin/simulations'
      path: '/simulations'
      fullPath: '/admin/simulations'
      preLoaderRoute: typeof AdminSimulationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expert-simulations': {
      id: '/admin/expert-simulations'
      path: '/expert-simulations'
      fullPath: '/admin/expert-simulations'
      preLoaderRoute: typeof AdminExpertSimulationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-prompts': {
      id: '/admin/ai-prompts'
      path: '/ai-prompts'
      fullPath: '/admin/ai-prompts'
      preLoaderRoute: typeof AdminAiPromptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/simulation/$id/feedback': {
      id: '/simulation/$id/feedback'
      path: '/feedback'
      fullPath: '/simulation/$id/feedback'
      preLoaderRoute: typeof SimulationIdFeedbackRouteImport
      parentRoute: typeof SimulationIdRoute
    }
    '/expert-simulation/$id/review': {
      id: '/expert-simulation/$id/review'
      path: '/expert-simulation/$id/review'
      fullPath: '/expert-simulation/$id/review'
      preLoaderRoute: typeof ExpertSimulationIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-simulation/$id/feedback': {
      id: '/expert-simulation/$id/feedback'
      path: '/expert-simulation/$id/feedback'
      fullPath: '/expert-simulation/$id/feedback'
      preLoaderRoute: typeof ExpertSimulationIdFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiPromptsRoute: typeof AdminAiPromptsRoute
  AdminExpertSimulationsRoute: typeof AdminExpertSimulationsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminSimulationsRoute: typeof AdminSimulationsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiPromptsRoute: AdminAiPromptsRoute,
  AdminExpertSimulationsRoute: AdminExpertSimulationsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminSimulationsRoute: AdminSimulationsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SimulationIdRouteChildren {
  SimulationIdFeedbackRoute: typeof SimulationIdFeedbackRoute
}

const SimulationIdRouteChildren: SimulationIdRouteChildren = {
  SimulationIdFeedbackRoute: SimulationIdFeedbackRoute,
}

const SimulationIdRouteWithChildren = SimulationIdRoute._addFileChildren(
  SimulationIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BizRoute: BizRoute,
  ExpertSimulationsRoute: ExpertSimulationsRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRoute,
  OnboardingRoute: OnboardingRoute,
  SimulationsRoute: SimulationsRoute,
  StartRoute: StartRoute,
  BizApplyRoute: BizApplyRoute,
  BizCoffeeChatRoute: BizCoffeeChatRoute,
  BizContactRoute: BizContactRoute,
  BizReviewRoute: BizReviewRoute,
  SimulationIdRoute: SimulationIdRouteWithChildren,
  SimulationsAllRoute: SimulationsAllRoute,
  ExpertSimulationIdFeedbackRoute: ExpertSimulationIdFeedbackRoute,
  ExpertSimulationIdReviewRoute: ExpertSimulationIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
