// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session

    // Server functions validate the bearer token independently. Refresh shortly
    // before expiry so a long-lived admin screen does not send a stale token.
    if (session?.expires_at && session.expires_at <= Math.floor(Date.now() / 1000) + 60) {
      const { data: refreshed, error } = await supabase.auth.refreshSession()
      if (!error && refreshed.session) session = refreshed.session
    }

    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
